<?php
/**
 * BroadbandCityFibreDetails
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BroadbandCityFibreDetails Class Doc Comment
 *
 * @category Class
 * @description Represents detailed information about CityFibre broadband in a specific area.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BroadbandCityFibreDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BroadbandCityFibreDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rfs_status' => 'string',
        'drop_architecture_type' => 'string',
        'demand_point_type' => 'string',
        'cabinet_area' => 'string',
        'cabinet_release_date' => '\DateTime',
        'property_classification' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rfs_status' => null,
        'drop_architecture_type' => null,
        'demand_point_type' => null,
        'cabinet_area' => null,
        'cabinet_release_date' => 'date-time',
        'property_classification' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rfs_status' => true,
        'drop_architecture_type' => true,
        'demand_point_type' => true,
        'cabinet_area' => true,
        'cabinet_release_date' => true,
        'property_classification' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rfs_status' => 'rfs_status',
        'drop_architecture_type' => 'drop_architecture_type',
        'demand_point_type' => 'demand_point_type',
        'cabinet_area' => 'cabinet_area',
        'cabinet_release_date' => 'cabinet_release_date',
        'property_classification' => 'property_classification'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rfs_status' => 'setRfsStatus',
        'drop_architecture_type' => 'setDropArchitectureType',
        'demand_point_type' => 'setDemandPointType',
        'cabinet_area' => 'setCabinetArea',
        'cabinet_release_date' => 'setCabinetReleaseDate',
        'property_classification' => 'setPropertyClassification'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rfs_status' => 'getRfsStatus',
        'drop_architecture_type' => 'getDropArchitectureType',
        'demand_point_type' => 'getDemandPointType',
        'cabinet_area' => 'getCabinetArea',
        'cabinet_release_date' => 'getCabinetReleaseDate',
        'property_classification' => 'getPropertyClassification'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rfs_status', $data ?? [], null);
        $this->setIfExists('drop_architecture_type', $data ?? [], null);
        $this->setIfExists('demand_point_type', $data ?? [], null);
        $this->setIfExists('cabinet_area', $data ?? [], null);
        $this->setIfExists('cabinet_release_date', $data ?? [], null);
        $this->setIfExists('property_classification', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rfs_status
     *
     * @return string|null
     */
    public function getRfsStatus()
    {
        return $this->container['rfs_status'];
    }

    /**
     * Sets rfs_status
     *
     * @param string|null $rfs_status Gets or sets the Ready For Service (RFS) status indicating whether the broadband service is available.
     *
     * @return self
     */
    public function setRfsStatus($rfs_status)
    {
        if (is_null($rfs_status)) {
            array_push($this->openAPINullablesSetToNull, 'rfs_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rfs_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rfs_status'] = $rfs_status;

        return $this;
    }

    /**
     * Gets drop_architecture_type
     *
     * @return string|null
     */
    public function getDropArchitectureType()
    {
        return $this->container['drop_architecture_type'];
    }

    /**
     * Sets drop_architecture_type
     *
     * @param string|null $drop_architecture_type Gets or sets the type of drop architecture used in the broadband connection.
     *
     * @return self
     */
    public function setDropArchitectureType($drop_architecture_type)
    {
        if (is_null($drop_architecture_type)) {
            array_push($this->openAPINullablesSetToNull, 'drop_architecture_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('drop_architecture_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['drop_architecture_type'] = $drop_architecture_type;

        return $this;
    }

    /**
     * Gets demand_point_type
     *
     * @return string|null
     */
    public function getDemandPointType()
    {
        return $this->container['demand_point_type'];
    }

    /**
     * Sets demand_point_type
     *
     * @param string|null $demand_point_type Gets or sets the demand point type, describing the type of endpoint for the broadband service.
     *
     * @return self
     */
    public function setDemandPointType($demand_point_type)
    {
        if (is_null($demand_point_type)) {
            array_push($this->openAPINullablesSetToNull, 'demand_point_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('demand_point_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['demand_point_type'] = $demand_point_type;

        return $this;
    }

    /**
     * Gets cabinet_area
     *
     * @return string|null
     */
    public function getCabinetArea()
    {
        return $this->container['cabinet_area'];
    }

    /**
     * Sets cabinet_area
     *
     * @param string|null $cabinet_area Gets or sets the cabinet area associated with the broadband service.
     *
     * @return self
     */
    public function setCabinetArea($cabinet_area)
    {
        if (is_null($cabinet_area)) {
            array_push($this->openAPINullablesSetToNull, 'cabinet_area');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cabinet_area', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cabinet_area'] = $cabinet_area;

        return $this;
    }

    /**
     * Gets cabinet_release_date
     *
     * @return \DateTime|null
     */
    public function getCabinetReleaseDate()
    {
        return $this->container['cabinet_release_date'];
    }

    /**
     * Sets cabinet_release_date
     *
     * @param \DateTime|null $cabinet_release_date Gets or sets the date when the cabinet was released or made available.  Nullable if the date is unknown or not applicable.
     *
     * @return self
     */
    public function setCabinetReleaseDate($cabinet_release_date)
    {
        if (is_null($cabinet_release_date)) {
            array_push($this->openAPINullablesSetToNull, 'cabinet_release_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cabinet_release_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cabinet_release_date'] = $cabinet_release_date;

        return $this;
    }

    /**
     * Gets property_classification
     *
     * @return string|null
     */
    public function getPropertyClassification()
    {
        return $this->container['property_classification'];
    }

    /**
     * Sets property_classification
     *
     * @param string|null $property_classification Gets or sets the classification of the property related to the broadband service.
     *
     * @return self
     */
    public function setPropertyClassification($property_classification)
    {
        if (is_null($property_classification)) {
            array_push($this->openAPINullablesSetToNull, 'property_classification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('property_classification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['property_classification'] = $property_classification;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


