<?php
/**
 * BroadbandSpeedTestData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BroadbandSpeedTestData Class Doc Comment
 *
 * @category Class
 * @description Represents a broadband speed test run
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BroadbandSpeedTestData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BroadbandSpeedTestData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ping' => 'float',
        'ping_data' => '\OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]',
        'jitter' => 'float',
        'jitter_data' => '\OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]',
        'download' => 'float',
        'download_data' => '\OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]',
        'upload' => 'float',
        'upload_data' => '\OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]',
        'date' => '\DateTime',
        'ip_address' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ping' => 'double',
        'ping_data' => null,
        'jitter' => 'double',
        'jitter_data' => null,
        'download' => 'double',
        'download_data' => null,
        'upload' => 'double',
        'upload_data' => null,
        'date' => 'date-time',
        'ip_address' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'ping' => true,
        'ping_data' => true,
        'jitter' => true,
        'jitter_data' => true,
        'download' => true,
        'download_data' => true,
        'upload' => true,
        'upload_data' => true,
        'date' => true,
        'ip_address' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ping' => 'Ping',
        'ping_data' => 'PingData',
        'jitter' => 'Jitter',
        'jitter_data' => 'JitterData',
        'download' => 'Download',
        'download_data' => 'DownloadData',
        'upload' => 'Upload',
        'upload_data' => 'UploadData',
        'date' => 'Date',
        'ip_address' => 'IPAddress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ping' => 'setPing',
        'ping_data' => 'setPingData',
        'jitter' => 'setJitter',
        'jitter_data' => 'setJitterData',
        'download' => 'setDownload',
        'download_data' => 'setDownloadData',
        'upload' => 'setUpload',
        'upload_data' => 'setUploadData',
        'date' => 'setDate',
        'ip_address' => 'setIpAddress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ping' => 'getPing',
        'ping_data' => 'getPingData',
        'jitter' => 'getJitter',
        'jitter_data' => 'getJitterData',
        'download' => 'getDownload',
        'download_data' => 'getDownloadData',
        'upload' => 'getUpload',
        'upload_data' => 'getUploadData',
        'date' => 'getDate',
        'ip_address' => 'getIpAddress'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ping', $data ?? [], null);
        $this->setIfExists('ping_data', $data ?? [], null);
        $this->setIfExists('jitter', $data ?? [], null);
        $this->setIfExists('jitter_data', $data ?? [], null);
        $this->setIfExists('download', $data ?? [], null);
        $this->setIfExists('download_data', $data ?? [], null);
        $this->setIfExists('upload', $data ?? [], null);
        $this->setIfExists('upload_data', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('ip_address', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ping
     *
     * @return float|null
     */
    public function getPing()
    {
        return $this->container['ping'];
    }

    /**
     * Sets ping
     *
     * @param float|null $ping Ping rate, in ms.
     *
     * @return self
     */
    public function setPing($ping)
    {
        if (is_null($ping)) {
            array_push($this->openAPINullablesSetToNull, 'ping');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ping', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ping'] = $ping;

        return $this;
    }

    /**
     * Gets ping_data
     *
     * @return \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null
     */
    public function getPingData()
    {
        return $this->container['ping_data'];
    }

    /**
     * Sets ping_data
     *
     * @param \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null $ping_data Ping Data
     *
     * @return self
     */
    public function setPingData($ping_data)
    {
        if (is_null($ping_data)) {
            array_push($this->openAPINullablesSetToNull, 'ping_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ping_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ping_data'] = $ping_data;

        return $this;
    }

    /**
     * Gets jitter
     *
     * @return float|null
     */
    public function getJitter()
    {
        return $this->container['jitter'];
    }

    /**
     * Sets jitter
     *
     * @param float|null $jitter Jitter rate, in ms
     *
     * @return self
     */
    public function setJitter($jitter)
    {
        if (is_null($jitter)) {
            array_push($this->openAPINullablesSetToNull, 'jitter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('jitter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['jitter'] = $jitter;

        return $this;
    }

    /**
     * Gets jitter_data
     *
     * @return \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null
     */
    public function getJitterData()
    {
        return $this->container['jitter_data'];
    }

    /**
     * Sets jitter_data
     *
     * @param \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null $jitter_data Jitter Data
     *
     * @return self
     */
    public function setJitterData($jitter_data)
    {
        if (is_null($jitter_data)) {
            array_push($this->openAPINullablesSetToNull, 'jitter_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('jitter_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['jitter_data'] = $jitter_data;

        return $this;
    }

    /**
     * Gets download
     *
     * @return float|null
     */
    public function getDownload()
    {
        return $this->container['download'];
    }

    /**
     * Sets download
     *
     * @param float|null $download Download rate, in Mbps
     *
     * @return self
     */
    public function setDownload($download)
    {
        if (is_null($download)) {
            array_push($this->openAPINullablesSetToNull, 'download');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('download', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['download'] = $download;

        return $this;
    }

    /**
     * Gets download_data
     *
     * @return \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null
     */
    public function getDownloadData()
    {
        return $this->container['download_data'];
    }

    /**
     * Sets download_data
     *
     * @param \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null $download_data Download data
     *
     * @return self
     */
    public function setDownloadData($download_data)
    {
        if (is_null($download_data)) {
            array_push($this->openAPINullablesSetToNull, 'download_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('download_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['download_data'] = $download_data;

        return $this;
    }

    /**
     * Gets upload
     *
     * @return float|null
     */
    public function getUpload()
    {
        return $this->container['upload'];
    }

    /**
     * Sets upload
     *
     * @param float|null $upload Upload rate, in Mbps
     *
     * @return self
     */
    public function setUpload($upload)
    {
        if (is_null($upload)) {
            array_push($this->openAPINullablesSetToNull, 'upload');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upload', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upload'] = $upload;

        return $this;
    }

    /**
     * Gets upload_data
     *
     * @return \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null
     */
    public function getUploadData()
    {
        return $this->container['upload_data'];
    }

    /**
     * Sets upload_data
     *
     * @param \OpenAPI\Client\Model\BroadbandSpeedTestDataPoint[]|null $upload_data Upload data
     *
     * @return self
     */
    public function setUploadData($upload_data)
    {
        if (is_null($upload_data)) {
            array_push($this->openAPINullablesSetToNull, 'upload_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upload_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upload_data'] = $upload_data;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \DateTime|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime|null $date Date when the speedtest was run
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            array_push($this->openAPINullablesSetToNull, 'date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets ip_address
     *
     * @return string|null
     */
    public function getIpAddress()
    {
        return $this->container['ip_address'];
    }

    /**
     * Sets ip_address
     *
     * @param string|null $ip_address IP address at which the test was run
     *
     * @return self
     */
    public function setIpAddress($ip_address)
    {
        if (is_null($ip_address)) {
            array_push($this->openAPINullablesSetToNull, 'ip_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip_address'] = $ip_address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


