<?php
/**
 * InvoiceSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InvoiceSummary Class Doc Comment
 *
 * @category Class
 * @description Represents a summary of an invoice
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InvoiceSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InvoiceSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'invoice_id' => 'int',
        'create_date' => '\DateTime',
        'due_date' => '\DateTime',
        'paid_status' => 'string',
        'payment_method' => 'string',
        'description' => 'string',
        'invoice_item_list' => '\OpenAPI\Client\Model\InvoiceItem[]',
        'invoice_sub_total' => 'float',
        'invoice_vat' => 'float',
        'invoice_total' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'invoice_id' => 'int32',
        'create_date' => 'date-time',
        'due_date' => 'date-time',
        'paid_status' => null,
        'payment_method' => null,
        'description' => null,
        'invoice_item_list' => null,
        'invoice_sub_total' => 'double',
        'invoice_vat' => 'double',
        'invoice_total' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'invoice_id' => false,
        'create_date' => false,
        'due_date' => false,
        'paid_status' => false,
        'payment_method' => false,
        'description' => true,
        'invoice_item_list' => true,
        'invoice_sub_total' => false,
        'invoice_vat' => false,
        'invoice_total' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'invoice_id' => 'invoice_id',
        'create_date' => 'create_date',
        'due_date' => 'due_date',
        'paid_status' => 'paid_status',
        'payment_method' => 'payment_method',
        'description' => 'description',
        'invoice_item_list' => 'invoice_item_list',
        'invoice_sub_total' => 'invoice_sub_total',
        'invoice_vat' => 'invoice_vat',
        'invoice_total' => 'invoice_total'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'invoice_id' => 'setInvoiceId',
        'create_date' => 'setCreateDate',
        'due_date' => 'setDueDate',
        'paid_status' => 'setPaidStatus',
        'payment_method' => 'setPaymentMethod',
        'description' => 'setDescription',
        'invoice_item_list' => 'setInvoiceItemList',
        'invoice_sub_total' => 'setInvoiceSubTotal',
        'invoice_vat' => 'setInvoiceVat',
        'invoice_total' => 'setInvoiceTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'invoice_id' => 'getInvoiceId',
        'create_date' => 'getCreateDate',
        'due_date' => 'getDueDate',
        'paid_status' => 'getPaidStatus',
        'payment_method' => 'getPaymentMethod',
        'description' => 'getDescription',
        'invoice_item_list' => 'getInvoiceItemList',
        'invoice_sub_total' => 'getInvoiceSubTotal',
        'invoice_vat' => 'getInvoiceVat',
        'invoice_total' => 'getInvoiceTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PAID_STATUS_UNPAID = 'Unpaid';
    public const PAID_STATUS_PAID = 'Paid';
    public const PAID_STATUS_OVERDUE = 'Overdue';
    public const PAID_STATUS_PROCESSING = 'Processing';
    public const PAID_STATUS_CANCELLED = 'Cancelled';
    public const PAID_STATUS_UNKNOWN = 'Unknown';
    public const PAYMENT_METHOD_NOT_PAID = 'Not_Paid';
    public const PAYMENT_METHOD_CHEQUE = 'Cheque';
    public const PAYMENT_METHOD_BACS = 'BACS';
    public const PAYMENT_METHOD_CREDIT_CARD = 'Credit_Card';
    public const PAYMENT_METHOD_OTHER = 'Other';
    public const PAYMENT_METHOD_DIRECT_DEBIT = 'Direct_Debit';
    public const PAYMENT_METHOD_CREDIT_CARD_AMEX = 'Credit_Card_Amex';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaidStatusAllowableValues()
    {
        return [
            self::PAID_STATUS_UNPAID,
            self::PAID_STATUS_PAID,
            self::PAID_STATUS_OVERDUE,
            self::PAID_STATUS_PROCESSING,
            self::PAID_STATUS_CANCELLED,
            self::PAID_STATUS_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentMethodAllowableValues()
    {
        return [
            self::PAYMENT_METHOD_NOT_PAID,
            self::PAYMENT_METHOD_CHEQUE,
            self::PAYMENT_METHOD_BACS,
            self::PAYMENT_METHOD_CREDIT_CARD,
            self::PAYMENT_METHOD_OTHER,
            self::PAYMENT_METHOD_DIRECT_DEBIT,
            self::PAYMENT_METHOD_CREDIT_CARD_AMEX,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('invoice_id', $data ?? [], null);
        $this->setIfExists('create_date', $data ?? [], null);
        $this->setIfExists('due_date', $data ?? [], null);
        $this->setIfExists('paid_status', $data ?? [], null);
        $this->setIfExists('payment_method', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('invoice_item_list', $data ?? [], null);
        $this->setIfExists('invoice_sub_total', $data ?? [], null);
        $this->setIfExists('invoice_vat', $data ?? [], null);
        $this->setIfExists('invoice_total', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPaidStatusAllowableValues();
        if (!is_null($this->container['paid_status']) && !in_array($this->container['paid_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'paid_status', must be one of '%s'",
                $this->container['paid_status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPaymentMethodAllowableValues();
        if (!is_null($this->container['payment_method']) && !in_array($this->container['payment_method'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_method', must be one of '%s'",
                $this->container['payment_method'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invoice_id
     *
     * @return int|null
     */
    public function getInvoiceId()
    {
        return $this->container['invoice_id'];
    }

    /**
     * Sets invoice_id
     *
     * @param int|null $invoice_id Result ID
     *
     * @return self
     */
    public function setInvoiceId($invoice_id)
    {
        if (is_null($invoice_id)) {
            throw new \InvalidArgumentException('non-nullable invoice_id cannot be null');
        }
        $this->container['invoice_id'] = $invoice_id;

        return $this;
    }

    /**
     * Gets create_date
     *
     * @return \DateTime|null
     */
    public function getCreateDate()
    {
        return $this->container['create_date'];
    }

    /**
     * Sets create_date
     *
     * @param \DateTime|null $create_date Create Date
     *
     * @return self
     */
    public function setCreateDate($create_date)
    {
        if (is_null($create_date)) {
            throw new \InvalidArgumentException('non-nullable create_date cannot be null');
        }
        $this->container['create_date'] = $create_date;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param \DateTime|null $due_date Due Date
     *
     * @return self
     */
    public function setDueDate($due_date)
    {
        if (is_null($due_date)) {
            throw new \InvalidArgumentException('non-nullable due_date cannot be null');
        }
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets paid_status
     *
     * @return string|null
     */
    public function getPaidStatus()
    {
        return $this->container['paid_status'];
    }

    /**
     * Sets paid_status
     *
     * @param string|null $paid_status Paid Status<p>Possible values:</p>  <ul>  <li><b>0</b> - Unpaid</li>  <li><b>1</b> - Paid</li>  <li><b>2</b> - Overdue</li>  <li><b>4</b> - Processing</li>  <li><b>5</b> - Cancelled</li>  <li><b>-1</b> - Unknown</li>  </ul>
     *
     * @return self
     */
    public function setPaidStatus($paid_status)
    {
        if (is_null($paid_status)) {
            throw new \InvalidArgumentException('non-nullable paid_status cannot be null');
        }
        $allowedValues = $this->getPaidStatusAllowableValues();
        if (!in_array($paid_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'paid_status', must be one of '%s'",
                    $paid_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['paid_status'] = $paid_status;

        return $this;
    }

    /**
     * Gets payment_method
     *
     * @return string|null
     */
    public function getPaymentMethod()
    {
        return $this->container['payment_method'];
    }

    /**
     * Sets payment_method
     *
     * @param string|null $payment_method Payment Method<p>Possible values:</p>  <ul>  <li><b>0</b> - Not Paid</li>  <li><b>1</b> - Cheque</li>  <li><b>2</b> - BACS</li>  <li><b>3</b> - Credit Card</li>  <li><b>5</b> - Other</li>  <li><b>6</b> - Direct Debit</li>  <li><b>7</b> - Credit Card Amex</li>  </ul>
     *
     * @return self
     */
    public function setPaymentMethod($payment_method)
    {
        if (is_null($payment_method)) {
            throw new \InvalidArgumentException('non-nullable payment_method cannot be null');
        }
        $allowedValues = $this->getPaymentMethodAllowableValues();
        if (!in_array($payment_method, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_method', must be one of '%s'",
                    $payment_method,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_method'] = $payment_method;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets invoice_item_list
     *
     * @return \OpenAPI\Client\Model\InvoiceItem[]|null
     */
    public function getInvoiceItemList()
    {
        return $this->container['invoice_item_list'];
    }

    /**
     * Sets invoice_item_list
     *
     * @param \OpenAPI\Client\Model\InvoiceItem[]|null $invoice_item_list Invoice Items
     *
     * @return self
     */
    public function setInvoiceItemList($invoice_item_list)
    {
        if (is_null($invoice_item_list)) {
            array_push($this->openAPINullablesSetToNull, 'invoice_item_list');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('invoice_item_list', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['invoice_item_list'] = $invoice_item_list;

        return $this;
    }

    /**
     * Gets invoice_sub_total
     *
     * @return float|null
     */
    public function getInvoiceSubTotal()
    {
        return $this->container['invoice_sub_total'];
    }

    /**
     * Sets invoice_sub_total
     *
     * @param float|null $invoice_sub_total Sub Total
     *
     * @return self
     */
    public function setInvoiceSubTotal($invoice_sub_total)
    {
        if (is_null($invoice_sub_total)) {
            throw new \InvalidArgumentException('non-nullable invoice_sub_total cannot be null');
        }
        $this->container['invoice_sub_total'] = $invoice_sub_total;

        return $this;
    }

    /**
     * Gets invoice_vat
     *
     * @return float|null
     */
    public function getInvoiceVat()
    {
        return $this->container['invoice_vat'];
    }

    /**
     * Sets invoice_vat
     *
     * @param float|null $invoice_vat VAT Total
     *
     * @return self
     */
    public function setInvoiceVat($invoice_vat)
    {
        if (is_null($invoice_vat)) {
            throw new \InvalidArgumentException('non-nullable invoice_vat cannot be null');
        }
        $this->container['invoice_vat'] = $invoice_vat;

        return $this;
    }

    /**
     * Gets invoice_total
     *
     * @return float|null
     */
    public function getInvoiceTotal()
    {
        return $this->container['invoice_total'];
    }

    /**
     * Sets invoice_total
     *
     * @param float|null $invoice_total Total
     *
     * @return self
     */
    public function setInvoiceTotal($invoice_total)
    {
        if (is_null($invoice_total)) {
            throw new \InvalidArgumentException('non-nullable invoice_total cannot be null');
        }
        $this->container['invoice_total'] = $invoice_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


