<?php
/**
 * TelecomsFaxPlan
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TelecomsFaxPlan Class Doc Comment
 *
 * @category Class
 * @description Represents fax plan pricing
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TelecomsFaxPlan implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TelecomsFaxPlan';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'non_geographic_price' => 'float',
        'geographic_price' => 'float',
        'credits10' => 'float',
        'credits100' => 'float',
        'credits500' => 'float',
        'credits1000' => 'float',
        'credits2000' => 'float',
        'credits5000' => 'float',
        'credits10000' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'non_geographic_price' => 'double',
        'geographic_price' => 'double',
        'credits10' => 'double',
        'credits100' => 'double',
        'credits500' => 'double',
        'credits1000' => 'double',
        'credits2000' => 'double',
        'credits5000' => 'double',
        'credits10000' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'non_geographic_price' => false,
        'geographic_price' => false,
        'credits10' => false,
        'credits100' => false,
        'credits500' => false,
        'credits1000' => false,
        'credits2000' => false,
        'credits5000' => false,
        'credits10000' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'non_geographic_price' => 'non_geographic_price',
        'geographic_price' => 'geographic_price',
        'credits10' => 'credits10',
        'credits100' => 'credits100',
        'credits500' => 'credits500',
        'credits1000' => 'credits1000',
        'credits2000' => 'credits2000',
        'credits5000' => 'credits5000',
        'credits10000' => 'credits10000'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'non_geographic_price' => 'setNonGeographicPrice',
        'geographic_price' => 'setGeographicPrice',
        'credits10' => 'setCredits10',
        'credits100' => 'setCredits100',
        'credits500' => 'setCredits500',
        'credits1000' => 'setCredits1000',
        'credits2000' => 'setCredits2000',
        'credits5000' => 'setCredits5000',
        'credits10000' => 'setCredits10000'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'non_geographic_price' => 'getNonGeographicPrice',
        'geographic_price' => 'getGeographicPrice',
        'credits10' => 'getCredits10',
        'credits100' => 'getCredits100',
        'credits500' => 'getCredits500',
        'credits1000' => 'getCredits1000',
        'credits2000' => 'getCredits2000',
        'credits5000' => 'getCredits5000',
        'credits10000' => 'getCredits10000'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('non_geographic_price', $data ?? [], null);
        $this->setIfExists('geographic_price', $data ?? [], null);
        $this->setIfExists('credits10', $data ?? [], null);
        $this->setIfExists('credits100', $data ?? [], null);
        $this->setIfExists('credits500', $data ?? [], null);
        $this->setIfExists('credits1000', $data ?? [], null);
        $this->setIfExists('credits2000', $data ?? [], null);
        $this->setIfExists('credits5000', $data ?? [], null);
        $this->setIfExists('credits10000', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets non_geographic_price
     *
     * @return float|null
     */
    public function getNonGeographicPrice()
    {
        return $this->container['non_geographic_price'];
    }

    /**
     * Sets non_geographic_price
     *
     * @param float|null $non_geographic_price Annual Price of non geographic Fax number.
     *
     * @return self
     */
    public function setNonGeographicPrice($non_geographic_price)
    {
        if (is_null($non_geographic_price)) {
            throw new \InvalidArgumentException('non-nullable non_geographic_price cannot be null');
        }
        $this->container['non_geographic_price'] = $non_geographic_price;

        return $this;
    }

    /**
     * Gets geographic_price
     *
     * @return float|null
     */
    public function getGeographicPrice()
    {
        return $this->container['geographic_price'];
    }

    /**
     * Sets geographic_price
     *
     * @param float|null $geographic_price Annual Price of geographic Fax number.
     *
     * @return self
     */
    public function setGeographicPrice($geographic_price)
    {
        if (is_null($geographic_price)) {
            throw new \InvalidArgumentException('non-nullable geographic_price cannot be null');
        }
        $this->container['geographic_price'] = $geographic_price;

        return $this;
    }

    /**
     * Gets credits10
     *
     * @return float|null
     */
    public function getCredits10()
    {
        return $this->container['credits10'];
    }

    /**
     * Sets credits10
     *
     * @param float|null $credits10 Cost of fax credit per 10 units.
     *
     * @return self
     */
    public function setCredits10($credits10)
    {
        if (is_null($credits10)) {
            throw new \InvalidArgumentException('non-nullable credits10 cannot be null');
        }
        $this->container['credits10'] = $credits10;

        return $this;
    }

    /**
     * Gets credits100
     *
     * @return float|null
     */
    public function getCredits100()
    {
        return $this->container['credits100'];
    }

    /**
     * Sets credits100
     *
     * @param float|null $credits100 Cost of fax credit per 100 units.
     *
     * @return self
     */
    public function setCredits100($credits100)
    {
        if (is_null($credits100)) {
            throw new \InvalidArgumentException('non-nullable credits100 cannot be null');
        }
        $this->container['credits100'] = $credits100;

        return $this;
    }

    /**
     * Gets credits500
     *
     * @return float|null
     */
    public function getCredits500()
    {
        return $this->container['credits500'];
    }

    /**
     * Sets credits500
     *
     * @param float|null $credits500 Cost of fax credit per 500 units.
     *
     * @return self
     */
    public function setCredits500($credits500)
    {
        if (is_null($credits500)) {
            throw new \InvalidArgumentException('non-nullable credits500 cannot be null');
        }
        $this->container['credits500'] = $credits500;

        return $this;
    }

    /**
     * Gets credits1000
     *
     * @return float|null
     */
    public function getCredits1000()
    {
        return $this->container['credits1000'];
    }

    /**
     * Sets credits1000
     *
     * @param float|null $credits1000 Cost of fax credit per 1000 units.
     *
     * @return self
     */
    public function setCredits1000($credits1000)
    {
        if (is_null($credits1000)) {
            throw new \InvalidArgumentException('non-nullable credits1000 cannot be null');
        }
        $this->container['credits1000'] = $credits1000;

        return $this;
    }

    /**
     * Gets credits2000
     *
     * @return float|null
     */
    public function getCredits2000()
    {
        return $this->container['credits2000'];
    }

    /**
     * Sets credits2000
     *
     * @param float|null $credits2000 Cost of fax credit per 2000 units.
     *
     * @return self
     */
    public function setCredits2000($credits2000)
    {
        if (is_null($credits2000)) {
            throw new \InvalidArgumentException('non-nullable credits2000 cannot be null');
        }
        $this->container['credits2000'] = $credits2000;

        return $this;
    }

    /**
     * Gets credits5000
     *
     * @return float|null
     */
    public function getCredits5000()
    {
        return $this->container['credits5000'];
    }

    /**
     * Sets credits5000
     *
     * @param float|null $credits5000 Cost of fax credit per 5000 units.
     *
     * @return self
     */
    public function setCredits5000($credits5000)
    {
        if (is_null($credits5000)) {
            throw new \InvalidArgumentException('non-nullable credits5000 cannot be null');
        }
        $this->container['credits5000'] = $credits5000;

        return $this;
    }

    /**
     * Gets credits10000
     *
     * @return float|null
     */
    public function getCredits10000()
    {
        return $this->container['credits10000'];
    }

    /**
     * Sets credits10000
     *
     * @param float|null $credits10000 Cost of fax credit per 10000 units.
     *
     * @return self
     */
    public function setCredits10000($credits10000)
    {
        if (is_null($credits10000)) {
            throw new \InvalidArgumentException('non-nullable credits10000 cannot be null');
        }
        $this->container['credits10000'] = $credits10000;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


