<?php
/**
 * BroadbandDiagnosticsTamFibreResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BroadbandDiagnosticsTamFibreResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a broadband diagnostics TAM response (additional information for fibre lines)
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BroadbandDiagnosticsTamFibreResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BroadbandDiagnosticsTamFibreResponse"
     */
    public function testBroadbandDiagnosticsTamFibreResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "report_fault"
     */
    public function testPropertyReportFault()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sync_status"
     */
    public function testPropertySyncStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voice_line_test_result"
     */
    public function testPropertyVoiceLineTestResult()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ethernet_traffic"
     */
    public function testPropertyEthernetTraffic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nte_power_status"
     */
    public function testPropertyNtePowerStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repetitive_electrical_impulse_noise"
     */
    public function testPropertyRepetitiveElectricalImpulseNoise()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "radio_frequency_ingress"
     */
    public function testPropertyRadioFrequencyIngress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bridge_tap"
     */
    public function testPropertyBridgeTap()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cross_talk"
     */
    public function testPropertyCrossTalk()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_downstream_speed"
     */
    public function testPropertyCurrentDownstreamSpeed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "current_upstream_speed"
     */
    public function testPropertyCurrentUpstreamSpeed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
