<?php
/**
 * BroadbandTroubleshootingApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Documentation
 *
 * The ICUK API provides an interface to the reseller control panel which can be used to control the provisioning and configuration of facilities remotely
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BroadbandTroubleshootingApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BroadbandTroubleshootingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for broadbandDlmResetPut
     *
     * Perform a DLM reset on a connection.
     *
     */
    public function testBroadbandDlmResetPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDlmResetResultsUsernameGet
     *
     * Obtain results from the DLM reset tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandDlmResetResultsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandDlmResetResultsUsernameIdGet
     *
     * Obtain results from the DLM reset tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandDlmResetResultsUsernameIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandInterleavingCurrentUsernameGet
     *
     * Retrieves the current interleaving option. Only available for users with BT Wholesale products.
     *
     */
    public function testBroadbandInterleavingCurrentUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandInterleavingPut
     *
     * Updates the interleaving profile. Only available for users with BT Wholesale broadband products.
     *
     */
    public function testBroadbandInterleavingPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortFlexPut
     *
     * Perform a port flex on a connection.
     *
     */
    public function testBroadbandPortFlexPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortFlexResultsUsernameGet
     *
     * Obtain results from the port flex tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortFlexResultsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortFlexResultsUsernameIdGet
     *
     * Obtain results from the port flex tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortFlexResultsUsernameIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortRebuildPut
     *
     * Perform a port rebuild on a connection.
     *
     */
    public function testBroadbandPortRebuildPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortRebuildResultsUsernameGet
     *
     * Obtain results from the port rebuild tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortRebuildResultsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortRebuildResultsUsernameIdGet
     *
     * Obtain results from the port rebuild tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortRebuildResultsUsernameIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortResetPut
     *
     * Perform a port reset on a connection.
     *
     */
    public function testBroadbandPortResetPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortResetResultsUsernameGet
     *
     * Obtain results from the port reset tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortResetResultsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandPortResetResultsUsernameIdGet
     *
     * Obtain results from the port reset tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandPortResetResultsUsernameIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandProfileCurrentUsernameGet
     *
     * Gets the current SNR and interleaving profile. Only available for users with TalkTalk products.
     *
     */
    public function testBroadbandProfileCurrentUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandProfilePut
     *
     * Updates SNR and interleaving profile. Only available for users with TalkTalk products.
     *
     */
    public function testBroadbandProfilePut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandSessionKillPut
     *
     * Perform a session kill on a connection.
     *
     */
    public function testBroadbandSessionKillPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandSessionKillResultsUsernameGet
     *
     * Obtain results from the session kill tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandSessionKillResultsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandSessionKillResultsUsernameIdGet
     *
     * Obtain results from the session kill tool. Returns the latest results, if no ID is specified.
     *
     */
    public function testBroadbandSessionKillResultsUsernameIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandSnrLogsUsernameGet
     *
     * Gets SNR logs for a user. Only available for users with BT Wholesale products.
     *
     */
    public function testBroadbandSnrLogsUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandSnrUsernameGet
     *
     * Reset the SNR of the user line. Only available for users with BT Wholesale products.
     *
     */
    public function testBroadbandSnrUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandStabilityCurrentUsernameGet
     *
     * Gets the current stability option of the line. The stability option will change once the order is complete.
     *
     */
    public function testBroadbandStabilityCurrentUsernameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for broadbandStabilityPut
     *
     * Updates the stability of the line.
     *
     */
    public function testBroadbandStabilityPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
